name: Deploy Angular
on:
  push:
    branches: ["main"]

#jobs
jobs:
  #name of the job and platform it will run (linux, windows or mac)
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 #used for running actions
      
      - name: Set up Nodejs
        uses: actions/setup-node@v3.3.0
        with:
          node-version: '18.x'
          cache: npm #cache and restore dependencies
      
      - name: Install Dependencies
        run: npm ci #npm ci is used for automated envs   

      #linting and unit tests
      - name: Tests
        run: npm run test:prod

      #build the app  
      - name: Build
        run: npm run build:prod  

      #setup in gh pages (edit the deploy-url on package.json build:prod script)  
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3    
        with:
          target_branch: gh-pages
          build_dir: dist/actions-angular 

